### PR TITLE
SSI on real data

### PR DESCRIPTION
**Pull request by b-biswas**
- [x] Add small catalogs to the data folder 
- [x] Perform SSI on real data 
- [x] clean workflow
- [x] scale up the simulations

### CODE REVIEW

**Comment by b-biswas** [comment]
@mpaillassa looks good to me! Let's merge this PR?

**Comment by mpaillassa** [comment]
Yes I think we can merge this !

**Comment by mpaillassa** [comment]
The additional changes you made look good to me !

**Comment by b-biswas** [comment]
Great I will merge this then!
I removed the hard-coded data path so that we can use the same code from different folders (eg. the notebooks and the scripts can now work with the same code)

**Pull request merged**
